[package]
name = "xac-tauri"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "xac_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.4.1", features = [] }

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2.9.1", features = [] }
xac-core = { path = "../crates/xac-core" }
xac-sim = { path = "../crates/xac-sim" }
